Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 1024
      Handler: com.devilelephant.fireholupdater.FireholUpdaterFn
      CodeUri: /Users/georgecoller/Workspace/cdk-lambda-packaging-java/software/FireholUpdater
      Runtime: java11
      Architectures:
        - x86_64