Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 2048
      Handler: com.devilelephant.blacklist.App
      CodeUri: /Users/georgecoller/Workspace/cdk-lambda-packaging-java/software/Blacklist
      Runtime: java11
      Architectures:
        - x86_64